---
title: "Chapter 3"
---

선물을 이용한 헷징전략  
*(Hedging Strategies Using Futures)*

## 기본 원리

기관이나 개인이 선물을 이용하여 리스크를 헷지한다는 것은, 기본적으로 **자신이 보유한 포지션이 지닌 가격변동위험과 반대 방향의 가격변동위험을 가진 선물계약을 보유**하는 것을 의미합니다.

즉, 현재 A회사의 포지션이 원달러 환율에 의한 가격변동위험에 노출되어 있어 **향후 3개월간 달러당 환율이 1원 오를때 1억원의 손실을 입는 구조**라면 달러당 환율이 **1원 오를때 1억원의 이익이 발생하는 3개월 만기 선물계약**을 보유하면 됩니다.

이렇게 되면, 향후 3개월간 달러당 환율이 10원 올라 나의 포지션에서 10억원의 손실이 발생하더라도 선물계약에서 10억원의 이익이 발생하여 **손익이 상쇄(offset)**됩니다. 따라서 선물계약을 체결한 시점 이후의 가격변동위험은 "0"이기 때문에 **A회사가 체감하는 환율의 실질가격(realized price, effective price)은 3개월간 선물계약의 체결가격으로 고정(lock)**됩니다. 이러한 과정을 **"헷징"**이라고 합니다.

::: {.callout-tip title="매도 헷지 vs. 매수 헷지"}
헷지 과정에서 선물을 매도하는 경우 매도 헷지(Short Hedges), 매수하는 경우 매수 헷지(Long Hedges)라고 합니다.\
**매도 헷지**는 특정 자산을 미래시점에 매도할 예정으로, 자산의 가격하락위험 회피를 목적으로 선물을 매도하여 가격이 하락하더라도 선물계약에서 이익이 발생하도록 하는 헷지 방법입니다. 주로 원자재 생산자, 수출업자 등 현재 자산을 보유하고있거나 보유할 예정으로 이를 판매할 목적인 경우 활용합니다.\
**매수 헷지**는 특정 자산을 미래시점에 매수할 예정으로, 자산의 가격상승위험 회피를 목적으로 선물을 매수하는 헷지 방법입니다. 주로 원자재를 이용하여 상품을 제조하는 제조업자, 수입업자 등 미래에 특정 자산을 구매할 목적인 경우 활용합니다.
:::

## 헷징에 대한 논쟁

회사가 본인이 직면한 리스크를 최소화할 수 있다는 점에서 **헷징의 중요성과 필요성은 명확**합니다. 파생상품을 이용하여 **적은 비용으로 리스크를 최소화하고, 본연의 경영활동에 집중**할 수 있기 때문입니다. 그러나, 실제로 헷징이 완벽하게 이루어지는 경우는 많지 않은데, 여기에는 다양한 이유들이 있습니다.

-   **헷징과 주주** : 회사가 직면한 리스크에 대해서, 대개 주주들은 이를 인지하고 직접 헷지하거나 포트폴리오를 다변화하여 관리합니다. 이 경우, 회사의 리스크 헷지를 주주들이 원하지 않을 수 있습니다.

-   **헷징과 경쟁자** : 산업군 내 경쟁자가 존재하고, 모든 경쟁자가 헷징을 하지 않는 경우 헷징이 경쟁에 불리하게 작용할 수 있습니다. 내가 헷징을 하지 않으면 가격변동위험에 노출되지만, 다른 경쟁사도 동일 위험에 노출되므로 경쟁력에는 영향이 없습니다. 반대로, 나만 헷징하는 경우 가격변동위험은 최소화되지만 향후 가격이 유리하게 변동하여 선물계약에서 손실이 발생한다면, 나에게만 손실이 발생하므로 경쟁력이 약화될 수 있습니다.

-   **헷징과 손익** : 선물을 이용한 헷징은 미래가격을 선물가격으로 고정시켜 가격변동위험을 없애는 것입니다. 향후 가격변동으로 인해 선물계약에서 이익이 발생할 수도, 손실이 발생할 수도 있습니다. 하지만, 때때로 의사결정자 또는 주주들은 헷징으로 인해 선물에서 평가손실이 발생하면 이를 납득하지 못하곤 합니다. 모든 의사결정자와 주주가 파생상품 메커니즘을 정확히 이해하기는 어렵기 때문입니다.

## 베이시스 리스크

선물을 이용한 헷징은 내가 보유한 자산에 대한 선물을 내가 헷지하고자 하는 기간에 대해 내가 보유한 수량만큼 매수하거나 매도하는 방식으로 이루어집니다. 하지만, 실제로 정확한 헷징은 매우 어렵습니다.\
  1. 선물의 **기초자산과 보유한 자산이 완벽히 동일**해야 합니다.\
  2. 내가 보유한 자산을 **언제까지 헷지할 것인지 정확히 알아야** 합니다.\
  3. 헷징 종료일과 선물 만기일이 항상 동일하지 않습니다. 이 경우, **헷징 종료시 선물계약을 처분**해야합니다.\
상기 이유들은 *베이시스 리스크*를 발생시키는 원인이 됩니다.

-   **베이시스(Basis)** : 베이시스란, 기초자산의 가격에서 선물가격을 차감한 값을 말합니다. $$Basis = Spot\;price - Futures\;price$$ 선물의 본질을 고려할 때, 선물가격은 현물가격과 유사하게 형성되며 만기일에는 현물가격으로 수렴하는 것을 직관적으로 알 수 있습니다. 따라서, **베이시스**는 0을 중심으로 움직이다가, **선물 만기일이 가까워지면서 0으로 수렴**하게 됩니다.\
    선물을 이용하여 헷지하는 경우, 일반적으로 선물 만기일 이전에 헷지를 종료하게 됩니다. 이때, 헷지종료시점에 선물가격($F_t$)은 현물가격($S_t$)과 다르므로 그 차이($B_2=F_2-S_2$)만큼 예기치 못한 손익이 발생합니다. 이를 ***베이시스 리스크***라고 합니다.\
    만약, 선물의 기초자산과 보유한 자산이 정확히 일치하지 않는 경우 헷지종료시점의 기초자산가격과 보유한 자산의 가격의 차이($S^*_t-S_t$)만큼 추가적인 손익이 발생합니다. 즉, *베이시스 리스크*가 확대되며 이러한 헷지를 *교차헷지*라고 합니다.

-   **선물계약 선택** : 베이시스 리스크 최소화를 위해서는 내가 보유한 자산과 **정확히 일치하거나 거의 유사한(**$corelation\approx 1$) 기초자산의 선물을, 헷지종료시점을 기준으로 가장 가까운 만기의 선물을 선택하는 것이 유리합니다. 다만, 실제로는 선물 유동성이 최근월물 위주로 형성되므로, 최근월물을 롤오버하는 방식이 많이 사용됩니다.

## 교차 헷지(*Cross Hedging*)

교차 헷지는 내가 보유한 자산과 선물의 기초자산이 같지 않은 경우를 말합니다. 항공사가 항공기 제트연료 가격 헷지를 위해 등유선물을 이용하는 것을 예로 들 수 있습니다.\
헷지비율(*hedge ratio*)은 보유자산의 명목금액 대비 선물계약의 명목금액의 비율로, 일반적으로 가격변동위험 최소화를 위해 1이 되도록 설정합니다.\
그러나, 교차 헷지를 해야하는 경우 헷지비율을 1로 설정해도 가격변동위험을 최소화되지 않을 수 있습니다. 이 경우, **보유 포트폴리오의 변동성이 최소화되는 헷지비율을 설정**해야 합니다.

-   **헷지비율 계산** : 먼저, 보유자산의 가격을 $S$, 선물가격을 $F$, 헷지비율을 $h$라고 하고 $S$와 $F$간에 선형성이 존재한다고 가정하면, 가격의 증분 $\Delta S$와 $\Delta F$를 아래와 같이 표현할 수 있습니다. $$\Delta S=a+b\Delta F+\epsilon$$ 이때, $h$만큼 매도헷지를 실행한 포트폴리오 가격의 증분은, $$\Delta S-h\Delta F=a+(b-h)\Delta F+\epsilon$$ 포트폴리오의 변동성 최소화를 위해서는 $h=b$임을 쉽게 알 수 있습니다.\
    따라서, 선형회귀분석으로 추정한 계수 $b$가 최적 헷지비율($h^*$)이 됩니다. $$h^*=b=\rho \frac{\sigma _S}{\sigma _F}$$ 이를 통해 보유자산과 선물 기초자산이 동일한 경우($\rho=1, \sigma _S=\sigma _F$)의 최적헷지비율은 1이 되며, 선물의 가격이 현물의 2배 민감도로 움직일 때($\sigma _F=2\sigma _S$) 최적헷지비율이 0.5가 되는 것을 이해할 수 있습니다.

-   **최적 계약 수** : 보유자산의 수량을 $Q_A$, 선물 1계약의 수량을 $Q_F$, 최적헷지비율을 $h^*$라고 하면, 최적헷지를 위한 선물계약 수 $N^*$는, $$N^*=\frac{h^* Q_A}{Q_F}$$

::: {.callout-note title="최적헷지비율 및 계약수 예시"}
제트연료 가격의 변동성을 $\sigma _A=0.1$, 등유선물 가격의 변동성을 $\sigma _F=0.2$, 제트연료와 등유선물 가격간 상관계수를 $\rho = 0.8$라고 하고, 헷지대상 제트연료가 200만 갤런 및 CME등유선물이 1계약당 4만갤런이라고 하자. 그러면, $$h^*=0.8*\frac{0.1}{0.2}=0.4$$ $$N^*=0.4*\frac{2,000,000}{40,000}=20contract$$
:::

-   **일일정산의 영향** : 현재까지는 일일정산이 없다고 가정하였으나, 실제 선물을 거래할 때는 오늘 선물의 종가로 보유선물계약을 평가하여 하루단위로 손익을 정산하고 있습니다.\
    **일일정산 반영**을 위해 앞선 수식을 **일수익률**을 기준으로 정리해보겠습니다. 보유자산 가격의 일수익률의 표준편차를 $\hat{\sigma}_S$, 선물가격의 일수익률의 표준편차를 $\hat{\sigma}_F$, 현물 및 선물의 일수익률간 상관계수를 $\hat{\rho}$라고 하면, $$h^*=\rho \frac{\sigma _S}{\sigma _F}=\hat{\rho} \frac{\hat{\sigma} _S S}{\hat{\sigma} _F F}$$ $$N^*=\frac{h^* Q_A}{Q_F}=\hat{\rho} \frac{\hat{\sigma} _S S Q_A}{\hat{\sigma} _F F Q_F}$$ 이제, 실제 가격변화를 사용한 최적헷지비율 $h^*$대신 일수익률을 이용한 최적헷지비율을 $\hat{h}^*$라고 하면, 아래와 같이 정리할 수 있습니다. $$\hat{h}^*=\hat{\rho} \frac{\hat{\sigma} _S}{\hat{\sigma} _F},\; N^*=\frac{\hat{h}^* V_A}{V_F}=\frac{\hat{h}^* A Q_A}{F Q_F}$$

::: {.callout-note title="최적헷지비율 및 계약수 예시2"}
제트연료 가격이 $1.1$, 등유선물 가격이 $1.2$, 제트연료와 등유선물 일수익률간 상관계수를 $\hat{\rho} = 0.8$라고 하고, 헷지대상 제트연료가 200만 갤런 및 CME등유선물이 1계약당 4만갤런이라고 하자. 그러면, 하루 헷지에 필요한 최적수량은 $$N^*=0.8*\frac{2,000,000 \times 1.1}{40,000 \times 1.2}=36.67$$
:::

## 주가지수선물

주가지수란, 주식 포트폴리오의 수익률을 추정하도록 설계한 지수를 말합니다. 일반적으로 구성종목을 정한 후, 동일한 비중 또는 시가총액(유통주식수\*주가)비율로 비중을 정하는 방식을 차용합니다. 보통 배당은 반영하지 않아 자본손익만을 추종하며, 구성종목의 주가 변동에 따라 지수의 구성비중이 실시간 변동하는 특징이 있습니다.

-   **주요 지수** : 미국의 대표적인 주가지수로는 다우존스30(DJIA), S&P500, Nasdaq100 등이 있고 중국의 CSI300 및 국내는 KOSPI200, KOSDAQ150 등이 있습니다.

-   **주식 포트폴리오 헷지** : 주가지수선물을 이용하여 주식 포트폴리오를 헷지할 때, 포트폴리오의 가치를 $V_A$, 주가지수선물 1계약의 가치를 $V_F$, 해당 지수에 대한 포트폴리오 베타를 $\beta$라고 하면 최적계약 수는 아래와 같습니다. $$N^*=\beta\frac{V_A}{V_F}$$ 만약 헷지기간 중 베타가 변동하는 경우, $(\beta - \beta ^*)\times\frac{V_A}{V_F}$만큼 선물계약을 조정해야 합니다.

-   **주식 포트폴리오를 헷지하는 이유** : 원문 책의 Table3.4를 참조하면, 주식포트폴리오 헷지를 통해 가격변동위험을 통제하고 나면 투자자가 얻는 수익은 무위험이자율 수준입니다.\
    여기서 한가지 근원적인 의문이 발생합니다. ***이자율 정도의 수익은 은행에 돈을 넣어두면 생기는데, 왜 주식포트폴리오를 매수하고 번거롭게 선물로 헷지하는 일을 해야하는거지?***\
    이에 대한 답으로는 "시장 전체의 위험(market risk)는 헷지하고 포트폴리오의 초과 수익($\alpha$)만 얻고싶은" 경우, "포트폴리오를 장기간 보유할 계획이나, 단기적으로 가격변동에 대한 헷지가 필요"한 경우 등이 있습니다.

::: {.callout-note title="시장위험 헷지 예시"}
현재 주식 포트폴리오의 가치는 200만 달러, 베타는 1.1, CME SnP500선물 1계약의 가치는 10만 달러라고 하자.\
시장 위험을 헷지하기 위한 최적계약수는 $N^*=1.1\times\frac{2,000,000}{100,000}=22$이고, 22계약을 매도하여 헷징포트폴리오를 구축하였다.\
선물 만기일에 S&P500지수는 20%하락, 나의 포트폴리오는 12%하락하였다면, 헷징포트폴리오는 -24만\$ 및 선물에서 +44만\$ 이익이 발생하여 합계 20만\$의 이익이 발생한다.\
즉, 시장은 전체적으로 하락하였으나 내 포트폴리오가 outperform하여 초과이익 $\alpha$가 발생한 것으로 해석할 수 있다.
:::

## 스택 앤 롤(*Stack And Roll*)

선물을 이용하여 헷지할 때, **헷지종료시점이 선물 만기일보다 나중**인 경우가 있습니다. 이때는 먼저 선물을 이용해 헷지한 다음, **만기일 직전에 선물 포지션을 청산함과 동시에 만기가 긴 선물로 새로운 포지션을 구축**하는 방법을 사용합니다. 이것이 *스택 앤 롤* 방법입니다.\
물론 헷지종료시점과 정확히 일치하는 선물을 사용하는 것이 가장 좋지만, **선물의 유동성은 만기가 짧은 종목에 집중**되어 있어 원하는 만기의 선물을 거래하기 어렵습니다. 실제로는 **가장 만기가 짧은 최근월물로 헷지**하고, **만기가 도래할 때마다 다음 최근월물로 갈아타는 *롤오버(Roll-over)* 방식**이 많이 사용됩니다.

::: {.callout-tip title="Stack and Roll의 위험성 : Metallgesellschaft 사례"}
Metallgesellschaft(이하, MG)는 독일의 원자재 회사로 등유와 가솔린을 판매하는 사업을 영위.\
판매계약은 향후 5\~10년까지 고정가격에 체결되어있어, MG는 원자재 가격상승위험 회피를 위해 선물을 매수하여 헷지 실행. 다만, 만기가 5\~10년 뒤인 선물은 거래가 어려워 최근월물을 롤오버하였는데, 여기서 단기적으로 원자재의 가격이 하락하면서 선물 포지션에서 손실이 누적됨.\
이를 만회하기 위해서는 판매대금을 받아야하는데, 미래시점의 판매대금을 미리 받을 수는 없어 현금흐름위험(cashflow risk)에 직면.\
결국 선물 포지션이 강제청산(margin call)되면서, 막대한 손실을 입음.
:::

## Appendix : CAPM {#sec-CAPM}

자본자산가격결정모형(CAPM, **C**apital **A**sset **P**ricing **M**odel)은 포트폴리오의 리스크 대비 기대수익률을 측정하는 모델입니다. 리스크는 시장 전체의 리스크로 분산(diversified)할 수 없는 *Systematic risk*와 분산할 수 있는 자산 고유의 위험인 *Nonsystematic risk*로 구성됩니다. CAPM 유도에 필요한 가정과 결과 산식은 다음과 같습니다.

1. 투자자는 기대수익률과 수익률의 표준편차만을 고려하여 투자자산을 결정한다.
2. 자산의 수익률은 시장의 수익률 대비 민감도 $\beta$로부터 산출된다.(Only one factor) 즉, 자산들간의 상관계수는 각 자산의 $\beta$의 비율과 같다.
3. 투자자는 한 투자기간에 대해서만 고려하며, 투자기간은 모든 투자자가 같다.
4. 투자자는 무위험수익률 $R_f$로 무한히 빌리거나 빌려줄 수 있다.
5. 세금은 고려하지 않는다.
6. 자산의 기대수익률과 표준편차, 상관계수는 모든 투자자에게 동일하다.

$$E(R_{portfolio})=R_f+\beta(R_{market}-R_f)$$