project:
  type: website

website:
  title: "Hyeonghwan"
  search: 
    location: navbar
    type: overlay
  navbar:
    background: primary
    left:
      - text: "HOME"
        file: home.qmd
      - text: "KAIST"
        href: home_study.qmd
      - text: "Baby"
        href: home_baby.qmd        
      - text: "Gaming"
        file: home_gaming.qmd
      - text: "Essay"
        file: "home_fe.qmd"
      - text: "Other life"
        file: home_life.qmd
    tools:
      - icon: google
        menu:
          - text: gudghks93@gmail.com
          - text: Send E-mail
            href: mailto:gudghks93@gmail.com
      - icon: github
        href: https://github.com/kimhyeonghwan
  sidebar: 
    - title: "Study"
      style: "docked"
      background: light
      contents:
        - text: "Study Home"
          file: home_study.qmd
        - text: "24년 봄학기"
          href: https://hwan.quarto.pub/24s
        - text: "24년 봄학기(선물옵션)"
          href: https://hwan.quarto.pub/derivatives
        - text: "24년 가을학기"
          href: https://hwan.quarto.pub/24f
        - text: "25년 봄학기"
        - text: "25년 가을학기(논문)"
    - title: "Baby"
      style: "docked"
      background: light
      contents:
        - text: "Baby Home"
          file: home_baby.qmd
        - text: "탄생의 순간"
          href: baby/baby1.qmd
        - text: "신생아 일기"
          href: baby/baby2.qmd

    - title: "Gaming"
      contents: gaming
    - title: "Essay"
      contents:
        - text: "Essay home"
          file: "home_essay.qmd"
        - text: "(1) 금융과 공학"
          file: fe/fe_1.qmd
        - text: "(2) 금융공학의 여러 분야"
          file: fe/fe_2.qmd
  page-footer: "Copyright 2024, Hyeonghwan Kim"
  back-to-top-navigation: true
  page-navigation: true 

execute:
  freeze: auto

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    linestretch : 2.5