project:
  type: website

website:
  title: "Hyeonghwan"
  search: 
    location: navbar
    type: overlay
  navbar:
    background: primary
    left:
      - text: "Home"
        file: home.qmd
      - text: "Study"
        href: home_study.qmd
      - text: "Life"
        file: home_life.qmd
    tools:
      - icon: github
        href: https://github.com/kimhyeonghwan
      - icon: google
        menu:
          - text: gudghks93@gmail.com
          - text: Send E-mail
            href: mailto:gudghks93@gmail.com
  sidebar: 
    - title: "Study"
      style: "docked"
      background: light
      contents:
        - text: "Study Home"
          file: home_study.qmd
        - text: "24년 봄학기"
          href: https://hwan.quarto.pub/24s
        - text: "24년 봄학기(선물옵션)"
          href: https://hwan.quarto.pub/derivatives
        - text: "24년 가을학기"
        - text: "25년 봄학기"
        - text: "25년 가을학기(논문)"
    - title: "Life"
      contents:
        - text: "Life Home"
          file: home_life.qmd
        - text: "일상"
        - text: "고양이"
        - text: "육아일기"
  page-footer: "Copyright 2024, Hyeonghwan Kim"
  back-to-top-navigation: true
  page-navigation: true 

execute:
  freeze: auto

format:
  html:
    theme: minty
    css: styles.css
    toc: true