project:
  type: website

website:
  title: "Hyeonghwan"
  search: 
    location: navbar
    type: overlay
  navbar:
    background: primary
    left:
      - text: "HOME"
        file: home.qmd
      - text: "KAIST"
        href: home_study.qmd
      - text: "LIFE"
        file: home_life.qmd
      - text: "금융공학"
        file: "home_fe.qmd"
    tools:
      - icon: google
        menu:
          - text: gudghks93@gmail.com
          - text: Send E-mail
            href: mailto:gudghks93@gmail.com
      - icon: github
        href: https://github.com/kimhyeonghwan
  sidebar: 
    - title: "KAIST"
      style: "docked"
      background: light
      contents:
        - text: "KAIST Home"
          file: home_study.qmd
        - text: "24년 봄학기"
          href: https://hwan.quarto.pub/24s
        - text: "24년 봄학기(선물옵션)"
          href: https://hwan.quarto.pub/derivatives
        - text: "24년 가을학기"
        - text: "25년 봄학기"
        - text: "25년 가을학기(논문)"
    - title: "금융공학"
      contents:
        - text: "금융공학 home"
          file: "home_fe.qmd"
        - text: "(1)금융과 공학"
          file: fe/fe_1.qmd
  page-footer: "Copyright 2024, Hyeonghwan Kim"
  back-to-top-navigation: true
  page-navigation: true 

execute:
  freeze: auto

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    linestretch : 3