{
  "hash": "6244ff75a9838caba700874ff1ba67eb",
  "result": {
    "engine": "knitr",
    "markdown": "# 투자분석 과제1 {.unnumbered}\n\n## ***Question***\n\nYou are a stock analyst and want to evaluate stocks. You may select any 3 stocks and get information from data source you prefer. You need a risk-free rate and market risk premium for this assignment. Choose appropriate risk-free rate such as 3-month T-bill rate or 1-month LIBOR and risk premium for the market portfolio. Use the constant growth dividend discount model. You may use any computer tool but do not hand in the data or the program code.\n\na) What are the names of stocks you choose? \nb) Specify risk-free rate, risk premium and the data source. \nc) What are the required rates of return? Use the CAPM. You need to specify firm’s beta and the expected rate of return of the market index portfolio.\nd) Calculate present value of growth opportunity (PVGO) for each stock.\ne) Find the intrinsic value (𝑉0) and 1-year value (𝑉1) for each stock.\nf) Find the expected rate of return for each stock, i.e., (𝑉1 − 𝑃0)/𝑃0 where 𝑃0 is the current market price.\ng) Based on the calculation above, which stock do you buy or sell? Explain briefly\n\n## 문제풀이\n\n### (a) 주식 선정\n\n저는 ***CME group(CME), ICE(ICE), Nasdaq(NDAQ)*** 세가지 종목을 선정하였습니다.\n\n선정 배경으로는,\n\n(1) 제가 거래소 산업에 관심이 많고,\n(2) 세 주식 모두 미국에 상장되어있는 대표적인 글로벌 거래소이며,\n(3) 동일한 거래소 산업이고 S&P500지수의 구성종목이라 동일 선상에서 비교하기 적합할 것으로 보이기 때문입니다.\n\n관련 자료는 [Yahoo Finance](https://finance.yahoo.com/)를 참조하였습니다.\n\n### (b) 무위험이자율 및 리스크프리미엄\n\nrisk-free rate는 최근 미국에서 대체지표금리로 선정한 SOFR기반의 금리를 누적하여 3개월 금리로 환산한 3-month SOFR Average를 risk-free rate로 선정하였습니다.\n\n[NewYork Fed : SOFR Average](https://www.newyorkfed.org/markets/reference-rates/sofr-averages-and-index)\n\n각 주식과 시장(S&P500)의 리스크프리미엄은 과거 3년간('21~'23)의 연평균수익률 및 무위험이자율을 이용하여 산출할 예정입니다.\n\n각 데이터를 취합하여 정리한 결과 및 무위험이자율, 리스크프리미엄의 산출은 아래와 같습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# import data&library\nrm(list = ls())\nlibrary(tidyverse)\nnasdaq <- read_csv(\"investment_hw/투자분석_NDAQ.csv\")\ncme <- read_csv(\"investment_hw/투자분석_CME.csv\")\nice <- read_csv(\"investment_hw/투자분석_ICE.csv\")\nrf <- read_csv(\"investment_hw/투자분석_sofrai.csv\")\nmarket <- read_csv(\"investment_hw/투자분석_snp500.csv\")\n\n# tidy data\nrf2 <- rf %>% \n  filter(`90-Day Average SOFR` %>% is.na()==FALSE) %>% \n  mutate(date=paste0(substr(`Effective Date`,7,10),\n                     substr(`Effective Date`,1,2),\n                     substr(`Effective Date`,4,5)) %>% as.integer(),\n         year=substr(`Effective Date`,7,10),\n         month=substr(`Effective Date`,1,2),\n         group=\"rfr\",\n         price=`90-Day Average SOFR`) %>% \n  select(year,month,date,group,price)\n\n# Data Pre-processing\ntidydata <- tibble()\ntidydata <- nasdaq %>% \n  mutate(group=\"nasdaq\") %>% \n  union_all(cme %>% mutate(group=\"cme\")) %>% \n  union_all(ice %>% mutate(group=\"ice\")) %>% \n  union_all(market %>% mutate(group=\"market\")) %>% \n  mutate(date=paste0(substr(Date,1,4),\n                     substr(Date,6,7),\n                     substr(Date,9,10)) %>% as.integer(),\n         year=substr(Date,1,4),\n         month=substr(Date,6,7),\n         price=`Adj Close`) %>% \n  select(year,month,date,group,price) %>% \n  union_all(rf2) %>% \n  arrange(date,group)\n\n# Use daily adj. closing price, if rfr is NA then use yesterday rfr.\ntidydata_wide <- tidydata %>% \n  pivot_wider(names_from = \"group\", values_from = \"price\") %>% \n  filter(nasdaq %>% is.na()==FALSE,\n         cme %>% is.na()==FALSE,\n         ice %>% is.na()==FALSE,\n         market %>% is.na()==FALSE) %>% \n  mutate(rfr=if_else(rfr %>% is.na(),lag(rfr)/100,rfr/100)) %>% \n  mutate(cme_yield=log(cme)-log(lag(cme)),\n         ice_yield=log(ice)-log(lag(ice)),\n         nasdaq_yield=log(nasdaq)-log(lag(nasdaq)),\n         market_yield=log(market)-log(lag(market))) %>% \n  filter(cme_yield %>% is.na()==FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrf3 <- tidydata_wide %>% \n  filter(year!=2020&year!=2024,as.integer(month)%%3==0) %>% \n  arrange(date %>% desc()) %>% \n  group_by(year,month) %>% \n  slice(1) %>% \n  ungroup() %>% \n  summarise(rfr_3year=mean(rfr))\n\ntidydata_wide %>% filter(date==20231229) %>% select(rfr) %>% bind_cols(rf3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n     rfr rfr_3year\n   <dbl>     <dbl>\n1 0.0536    0.0223\n```\n\n\n:::\n\n```{.r .cell-code}\ntidydata_wide %>% \n  filter(year!=2020&year!=2024) %>% \n  summarise(cme_premium=sum(cme_yield)/3-rf3$rfr_3year,\n            ice_premium=sum(ice_yield)/3-rf3$rfr_3year,\n            nasdaq_premium=sum(nasdaq_yield)/3-rf3$rfr_3year,\n            market_premium=sum(market_yield)/3-rf3$rfr_3year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  cme_premium ice_premium nasdaq_premium market_premium\n        <dbl>       <dbl>          <dbl>          <dbl>\n1      0.0679      0.0272         0.0826         0.0573\n```\n\n\n:::\n:::\n\n\n무위험이자율은 기간말 기준 5.36%, 과거 3개년 동안 무위험이자율에 투자한 연평균수익률은 약 2.23%, 과거 3개년 동안 실현된 각 주식과 시장의 연환산 리스크프리미엄은 아래 표와 같습니다.\n\n|구 분|S&P500|CME|ICE|NASDAQ|\n|:----:|:----:|:----:|:----:|:----:|\n|연수익률|7.96%|9.03%%|4.95%|10.49%|\n|프리미엄|5.74%|6.81%%|2.73%|8.27%|\n\n::: {.callout-warning title=\"Excess return vs. Risk premium\"}\n초과수익률은 과거의 값을 바탕으로 산출되며, 리스크프리미엄은 기대수익률을 기반으로 산출.\n\n위의 풀이는 초과수익률을 산출하였으므로 오답이며, 리스크프리미엄은 CAPM 등의 기대수익률을 가지고와서 산출해야 함.\n$$Excess\\;return = r-r_f$$\n$$Risk\\;premium = E[r]-r_f$$\n:::\n\n### (c) CAPM\n\n각 종목의 베타를 산출하기 위해 필요한 파라미터는 아래와 같습니다.\n\n- 무위험이자율, $R_f$ : 기간말('23.12월말)의 3-month SOFR average\n- 시장수익률, $R_m$ : S&P500지수의 수익률\n- 개별수익률, $R_{stock}$ : 개별 주식의 수익률\n\n수익률은 일간/월간 두가지를 사용하여 비교할 예정이며, 회귀분석에 사용한 값은 아래와 같습니다.\n\n- 기간 : (일별) 2023년 250거래일, (월간) 2021년~2023년 36개월\n- 산출방법 : (일별) 전일 종가 대비 당일 종가의 로그수익률, (월별) 이전달 말 종가 대비 이번달 말 종가의 로그수익률\n\n마지막으로, 베타를 이용하여 기대수익률을 산출할 때 이용한 $R_m$은 다음과 같습니다.\n\n- (일별) 250일간 S&P500지수 일평균수익률의 연환산(=연수익률)\n- (월별) 36개월간 S&P500지수 월평균수익률의 연환산(=3개년수익률/3)\n\n::: {.callout-warning}\n로그수익률(연속복리수익률)을 사용하였으므로 보유기간수익률로 표현할 때 단순 덧셈만으로 환산할 수 있습니다.\n\n또한, 기간 중 배당 및 CA로 인한 차이는 수정주가(Adj. close price)를 사용해서 보정하였습니다.\n:::\n\n이에 따라, R코드로 산출한 개별종목별 **베타 / 기대수익률 / 산출기간동안 실현수익률**은 아래와 같습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calcuate beta, required return\n\n# daily beta in '23\ndailybeta <- tidydata_wide %>% \n  filter(year==\"2023\") %>% \n  summarise(beta_cme=cov(market_yield,cme_yield)/var(market_yield),\n            beta_ice=cov(market_yield,ice_yield)/var(market_yield),\n            beta_nasdaq=cov(market_yield,nasdaq_yield)/var(market_yield),\n            market_avg_yield=sum(market_yield),\n            cme_avg_yield=sum(cme_yield),\n            ice_avg_yield=sum(ice_yield),\n            nasdaq_avg_yield=sum(nasdaq_yield)) %>% \n  mutate(group=\"daily\")\n\n# monthly beta\nmonthlybeta <- tidydata_wide %>% \n  arrange(year,month,date %>% desc) %>% \n  group_by(year,month) %>% \n  slice(1) %>% \n  ungroup() %>% \n  mutate(cme_yield=log(cme)-log(lag(cme)),\n         ice_yield=log(ice)-log(lag(ice)),\n         nasdaq_yield=log(nasdaq)-log(lag(nasdaq)),\n         market_yield=log(market)-log(lag(market))) %>% \n  filter(cme_yield %>% is.na()==FALSE) %>% \n  filter(year!=\"2024\",year!=\"2020\") %>% \n  summarise(beta_cme=cov(market_yield,cme_yield)/var(market_yield),\n            beta_ice=cov(market_yield,ice_yield)/var(market_yield),\n            beta_nasdaq=cov(market_yield,nasdaq_yield)/var(market_yield),\n            market_avg_yield=sum(market_yield)/3,\n            cme_avg_yield=sum(cme_yield)/3,\n            ice_avg_yield=sum(ice_yield)/3,\n            nasdaq_avg_yield=sum(nasdaq_yield)/3) %>% \n  mutate(group=\"monthly\")\n\nbeta <- tibble()\nbeta <- dailybeta %>% \n  union_all(monthlybeta) %>% \n  mutate(tidydata_wide %>% filter(date==20231229) %>% select(rfr)) %>% \n  select(group,market_avg_yield,cme_avg_yield,ice_avg_yield,nasdaq_avg_yield,\n         rfr,beta_cme,beta_ice,beta_nasdaq)\n\ncapm <- tibble()\ncapm <- beta %>% \n  pivot_longer(cols = c(\"beta_cme\",\"beta_ice\",\"beta_nasdaq\"),\n               names_to = \"stock\", values_to = \"beta\") %>% \n  mutate(expected_return=beta*(market_avg_yield-rfr)+rfr) %>% \n  mutate(stock=substr(stock,6,nchar(stock))) %>% \n  mutate(realized_return=if_else(stock==\"cme\",cme_avg_yield,\n                                if_else(stock==\"ice\",ice_avg_yield,nasdaq_avg_yield))) %>% \n  select(group,stock,beta,expected_return,realized_return,market_avg_yield,rfr)\n\ncapm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  group   stock   beta expected_return realized_return market_avg_yield    rfr\n  <chr>   <chr>  <dbl>           <dbl>           <dbl>            <dbl>  <dbl>\n1 daily   cme    0.315          0.105           0.272            0.217  0.0536\n2 daily   ice    0.828          0.189           0.240            0.217  0.0536\n3 daily   nasdaq 0.866          0.195          -0.0373           0.217  0.0536\n4 monthly cme    0.353          0.0628          0.0903           0.0796 0.0536\n5 monthly ice    1.12           0.0829          0.0495           0.0796 0.0536\n6 monthly nasdaq 0.993          0.0795          0.105            0.0796 0.0536\n```\n\n\n:::\n:::\n\n\n일별/월별로 구분한 각 주식의 베타와 기대수익률입니다.\n\n보다 일반적이고 평탄화된 결과를 위해 월별 데이터를 중심으로 설명하겠습니다.\n\n먼저 **각 주식의 베타는 CME:0.35, ICE:1.12, Nasdaq 0.99**입니다. 이는 거래소산업이 특성상 변동성이 크지 않고 경제상황에 민감하지 않아 베타가 시장포트폴리오와 유사한 1 수준에서 형성되는 것으로 보입니다. 특히, CME는 세계 최대의 파생상품거래소로서 규모가 매우 큰 고배당 우량주인 특징이 있어 변동성이 낮아 베타가 0.35로 낮게 형성된 것으로 추정됩니다.\n\n::: {.callout title=\"베타 산출방법\"}\n베타는 $R_{stock,t}=\\alpha+\\beta R_{m,t}+\\epsilon$의 선형회귀분석 결과로 산출되는 계수입니다.\n\n즉, $\\beta=\\rho_{stock,m}\\frac{\\sigma_{stock}}{\\sigma_m}=\\frac{Cov_{stock,m}}{\\sigma_m^2}$로 산출할 수 있습니다.\n:::\n\n월별수익률을 산출한 과거 3년(2021~2023)간 평균월별수익률을 연율화하면 로그수익률 특성상 지난 3년간 연평균수익률과 같습니다. 즉, 시장포트폴리오의 기대수익률은 약 7.96%라고 할 수 있으며, 무위험이자율은 2023.12월말 값인 5.36%를 사용합니다.\n\n이제, $R_{stock}=\\beta(R_m-R_f)+R_f$를 통해 각 주식의 요구수익률을 산출할 수 있습니다.\n\n|구 분|CME|ICE|NASDAQ|\n|:----:|:-----:|:-----:|:-----:|\n|Beta|0.35|1.12|0.99|\n|Required Return|6.28%|8.29%|7.95%|\n\n### (d) PVGO\n\n먼저, 거래소산업은 성장주보다는 우량주 성향이 강하고, 배당성향이 다소 높고 정기적인 배당을 하는 경향이 있습니다.. 따라서 배당할인모형(Constant-growth DDM)을 사용할 예정입니다.\n\n먼저, 기업의 내재가치에 배당할인모형을 적용한 PVGO의 산식은 아래와 같습니다.\n$$PVGO=V_0-\\frac{E_1}{k}=\\frac{D_1}{k-g}-\\frac{E_1}{k}$$\n\n여기서, 요구수익률 $k$는 (c)에서 CAPM으로 구한 요구수익률을 사용할 예정이며, $D_1, E_1, g$를 구하기 위해 직전주당배당($D_0$), 직전 주당수익($E_0$), 직전재투자성향($b_0=\\frac{E_0-D_0}{E_0}$), 직전 자기자본수익률 $ROE_0$를 이용하여 다음과 같이 산출하도록 하겠습니다.\n\n$$g=b_0\\times ROE_0=\\frac{E_0-D_0}{E_0}\\times ROE_0,\\;\\;D_1=D_0(1+g),\\;\\;E_1=E_0(1+g)$$\n\n$$\\Rrightarrow PVGO=\\frac{D_0(1+g)}{k-g}-\\frac{E_0(1+g)}{k}$$\n\n::: {.callout-note title=\"주당순이익 산출 : DDM\"}\n다음 년도의 주당순이익 $E_1$은 올해의 순이익 $E_0$에 배당할인모형의 배당성장률 $g$를 반영하여 산출하였습니다.\n:::\n\n이제, 각 주식의 재무상태표를 참조하여 $D_0$, $E_0$, $b_0$, $ROE_0$를 산출하겠습니다. 다만, 직전사업연도(2023)는 시장벤치마크(S&P500)의 수익률이 약 21%로, 과거 평균치의 약 3배를 상회하고 있어 각 기업의 EPS, DPS 등이 평소 수치보다 고평가되었을 가능성이 있습니다. 이를 감안하여 $D_0$, $E_0$ 산출시에는 과거 3개년 당기순이익, 현금배당금의 산술평균을 사용할 것이며 $ROE_0$는 과거 3개년의 기하평균을 사용하겠습니다.\n\n각 값들은 [Yahoo Finance](https://finance.yahoo.com/) 및 [Stockrow](https://stockrow.com/)를 참조하였습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinancial <- read_csv(\"investment_hw/투자분석_financialstatement.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# DDM 이용\nfinancial <- financial %>% \n  group_by(stock) %>% \n  summarise(eps=sum(earning)/sum(shares),\n            dps=sum(dividend)/sum(shares),\n            bps=sum(capital)/sum(shares),\n            roe=prod(1+roe)^(1/3)-1) %>% \n  mutate(reinvestment=(eps-dps)/eps) %>% \n  mutate(growth=roe*reinvestment) %>% \n  mutate(d1=dps*(1+growth),\n         e1=eps*(1+growth)) %>% \n  left_join(.,capm %>% filter(group==\"monthly\") %>% select(stock,expected_return,rfr),\n            by=\"stock\") %>% \n  mutate(v0_ddm=d1/(expected_return-growth)) %>% \n  mutate(pvgo_ddm=v0_ddm-e1/expected_return)\nfinancial\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 13\n  stock   eps   dps   bps   roe reinvestment  growth    d1    e1 expected_return\n  <chr> <dbl> <dbl> <dbl> <dbl>        <dbl>   <dbl> <dbl> <dbl>           <dbl>\n1 cme    7.86 7.49   75.3 0.105       0.0475 0.00497 7.53   7.90          0.0628\n2 ice    4.67 1.52   42.3 0.116       0.675  0.0786  1.64   5.04          0.0829\n3 nasd…  2.25 0.785  15.6 0.163       0.652  0.106   0.868  2.49          0.0795\n# ℹ 3 more variables: rfr <dbl>, v0_ddm <dbl>, pvgo_ddm <dbl>\n```\n\n\n:::\n:::\n\n\n산출 결과는 아래와 같습니다.\n\n|구 분|CME|ICE|NASDAQ|\n|:----:|:-----:|:-----:|:-----:|\n|$E_0$|7.86|4.67|2.25|\n|$D_0$|7.49|1.52|0.79|\n|$ROE_0$|10.5%|11.6%|16.3%|\n|$b_0$|4.7%|67.5%|65.2%|\n|$g$|0.5%|7.9%|10.6%|\n|$D_1$|7.53|1.64|0.87|\n|$E_1$|7.90|5.04|2.49|\n|$k$|6.28%|8.29%|7.95%|\n|$V_0$|130.15|380.07|-32.82(NaN)|\n|$PVGO$|4.32|319.28|-64.19(NaN)|\n\n배당할인모형을 사용하여 평가해본 결과, **PVGO는 CME가 4.32\\$, ICE가 319.28\\$, NASDAQ은 -64.19\\$로 산출**되었습니다. 여기서 **NASDAQ 거래소**의 경우 **기업의 요구수익률보다 성장률이 높아($k<g$)** 기업의 내채가치($V_0$) 평가에 **배당할인모형을 사용할 수 없는 케이스**입니다. 즉, **PVGO가 정상적으로 산출되지 않았습니다.**\n\nNASDAQ 거래소의 요구수익률은 7.95% 및 성장률은 10.6%로 산출되었는데, 현재시점에서 배당할인모형을 통해 이 주식을 평가한다는 것은 기업에 요구되는 수익률보다 성장하는 속도가 높아서 기업의 미래 배당가치가 발산($\\rightarrow\\infty$)한다는 것을 의미합니다. 이러한 이유가 발생하는 이유를 추정해보면, 아마도 NASDAQ의 현재주가가 저평가되어있거나, 최근 성과가 좋아서 단기적으로 $ROE_0$가 높게 산출되었거나, CAPM의 요구수익률이 실제 주식의 요구수익률보다 낮기 때문일 것 입니다.\n\nNASDAQ 거래소의 과거 추이를 볼 때, 최근 3년간 실현수익이 연평균 약 10.5%로 요구수익률보다 높고 성장률과 유사하므로 CAPM의 요구수익률이 실제 주식의 요구수익률을 정확하게 평가하지 못한 것이 주된 이유일 것으로 보입니다.\n\n이러한 문제점은,\n\n(1) CAPM 대신 APT 등의 다른 모형으로 요구수익률($k$)을 평가해보거나,\n\n(2) 배당할인모형(DDM) 대신 다른 모형을 이용함으로써 해결할 수 있습니다.\n\n::: {.callout-note title=\"CAPM의 한계\"}\nCAPM으로 산출한 요구수익률 $k$는 개별주식의 여러 특성을 정확히 반영하지 못하였을 가능성이 있습니다. CAPM은 시장에 대한 민감도 $\\beta$와 시장포트폴리오의 리스크 대비 수익률($R_m-R_f$)을 이용해 주가의 기대수익률(요구수익률)을 평가하는데, 이 한가지 요인(factor)으로 기대수익률이 결정된다고 가정하기 때문입니다.\n:::\n\nMulti-factor 모형은 배우기 이전이므로 수업시간에 배운 **초과이익모형(Residual Income Model)을 이용하여 세 주식의 $V_0$, $PVGO$를 다시 평가**해보도록 하겠습니다.\n\n먼저, RIM의 산식은 다음과 같습니다.\n\n$$V_0=BE_0+\\sum_{i=1}^\\infty \\frac{E[RE_i]}{(1+k)^i}$$\n\n여기서 $BE_0$은 주당순자산으로 $D_0,\\;E_0$과 같이 과거 3개년 평균치를 사용하고, 초과이익의 기대값 $E[RE_i]$는 $i$년도의 주당순이익($E_i$)-주당배당금($D_i$)으로 결정되며, 주당순이익은 $E_i=ROE_0\\times BE_{i-1}$, 주당배당금은 $k\\times BE_{i-1}$로 산출, $BE_{i}=BE_{i-1}\\times (1+R_f)$(즉, 초과이익이 무위험이자율만큼 성장)하도록 하겠습니다.\n\n$$V_0=BE_0+\\sum_{i=1}^\\infty \\frac{(ROE_0-k)BE_0(1+r_f)^i}{(1+k)^i}=BE_0+\\frac{(ROE_0-k)BE_0}{k-r_f}$$\n\n위와 같이 RIM으로 기업의 내재가치를 산출할 수 있으며, 산출결과는 아래와 같습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinancial_rim <- financial %>% \n  mutate(v0_rim=bps+(roe-expected_return)*bps/(expected_return-rfr)) %>%\n  mutate(pvgo_rim=v0_rim-(eps*(1+rfr))/expected_return) %>% \n  select(stock,bps,roe,rfr,expected_return,v0_rim,pvgo_rim)\n\nfinancial_rim\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  stock    bps   roe    rfr expected_return v0_rim pvgo_rim\n  <chr>  <dbl> <dbl>  <dbl>           <dbl>  <dbl>    <dbl>\n1 cme     75.3 0.105 0.0536          0.0628  417.     285. \n2 ice     42.3 0.116 0.0536          0.0829   90.5     31.2\n3 nasdaq  15.6 0.163 0.0536          0.0795   65.8     35.9\n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"주당순이익 산출 : RIM\"}\n다음 년도의 주당순이익 $E_1$은 올해의 순이익 $E_0$에 초과이익성장률인 무위험이자율만큼 가산하여 산출하였습니다.\n:::\n\n|구 분|CME|ICE|NASDAQ|\n|:----:|:-----:|:-----:|:-----:|\n|$V_0,\\; DDM$|130.15|380.07|-|\n|$PVGO,\\; DDM$|4.32|319.28|-|\n|$V_0,\\; RIM$|417.10|90.55|65.81|\n|$PVGO,\\; RIM$|291.86|34.20|37.43|\n\nRIM 방식으로 내재가치를 평가한 결과, **PVGO의 값은 CME가 291.86\\$, ICE가 34.20\\$, NASDAQ에서 37.43\\$로 산출**되었습니다.\n\n### (e) Find $V_0,\\;V_1$\n\n제가 사용한 RIM 산출식에서 $V_1=V_0(1+r_f)$입니다. (DDM은 $V_1=V_0(1+g)$)\n\nNASDAQ에서 DDM은 사용할 수 없으므로 RIM을 기준으로 산출하겠습니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinancial_rim %>% \n  mutate(v1_rim=v0_rim*(1+rfr)) %>% \n  select(stock,v0_rim,v1_rim)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  stock  v0_rim v1_rim\n  <chr>   <dbl>  <dbl>\n1 cme     417.   439. \n2 ice      90.5   95.4\n3 nasdaq   65.8   69.3\n```\n\n\n:::\n:::\n\n\n기존에 산출하였던 $V_0$와 산출한 $V_1$은 아래와 같습니다.\n\n|구 분|CME|ICE|NASDAQ|\n|:----:|:-----:|:-----:|:-----:|\n|$V_0,\\; RIM$|417.10|90.55|65.81|\n|$V_1,\\; RIM$|439.44|95.40|69.33|\n\n### (f) Find the expected rate of return for each stock\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstock_return <- financial_rim %>% \n  mutate(v1_rim=v0_rim*(1+rfr)) %>% \n  select(stock,v1_rim) %>% \n  left_join(.,tidydata %>% filter(date==20240228) %>% select(group,price),\n            by=c('stock'='group')) %>% \n  mutate(return=(v1_rim-price)/price)\nstock_return\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  stock  v1_rim price return\n  <chr>   <dbl> <dbl>  <dbl>\n1 cme     439.  220.   1.00 \n2 ice      95.4 138.  -0.311\n3 nasdaq   69.3  56.1  0.236\n```\n\n\n:::\n:::\n\n\n\n2월말 기준 각 주식의 종가를 기준으로 계산한 **연환산 기대수익률**은 다음과 같습니다. \n\n|구 분|CME|ICE|NASDAQ|\n|:----:|:-----:|:-----:|:-----:|\n|$V_1,\\; RIM$|439.44|95.40|69.33|\n|$Close Price$|219.68|138.39|56.11|\n|**$Expected Return,\\; annum$**|100.03%|-31.06%|23.55%|\n\n### (g) Which stock is the best?\n\n#### **NASDAQ exchange 주식**\n\n단순히 (f)의 기대수익률로 볼 때는 CME가 가장 높지만, 이는 BPS가 높고 배당성향이 1에 가까운 CME 거래소의 특성상 RIM 방식에서 높은 내재가치를 평가받은 것으로 보입니다. 이는 DDM 방식으로 평가하였을 때, 성장률 $g$가 매우 낮아 내재가치가 다소 낮게 산출된 점에서 잘 드러납니다.\n\n또한, CME는 시장 베타도 0.35수준으로 낮아 절대적인 요구수익률이 높지 않고 변동성도 낮아 흔히 말하는 재미없는 주식입니다. 장기적인 투자를 선호하고 자본금이 많은 기관투자자 등이 주로 투자하는 주식일 것으로 예상됩니다.\n\n반면에 NASDAQ은 RIM방식으로 평가한 기대수익률이 연 23.55% 수준으로 양호하고, 시장 베타도 거의 1에 가까워 적당한 변동성을 가지고 있습니다. DDM방식에서는 평가가 불가능하였으나, 이 의미는 ROE와 배당성향이 높아 기대되는 배당성장률 $g$가 CAPM의 요구수익률 $k$보다 높다는 뜻입니다. 즉, 초과이익을 발생시켜 시장을 outperform할 확률이 높다고 생각하였습니다.\n\n즉, **배당성향이 매우 높고 변동성이 낮아 안정적인 우량주인 CME보다**는 최근 성과가 훌륭하여 **성장성이 있으며, 안정적으로 요구수익률 대비  초과이익**을 달성할 것으로 예상되고, **적정 수준의 변동성을 지닌 NASDAQ 거래소이 투자대상으로 가장 적합**하다고 판단됩니다.\n\n한편, ICE는 DDM에서는 내재가치가 좋게 평가되었으나 RIM에서는 낮게 평가되어 결국 기대수익률이 (-)되는 분석결과를 고려하여 선택하지 않았습니다.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}