---
title: "금융과 공학"
---

### Intro

첫번째로 제가 생각하는 금융공학을 정의해보려고 합니다.

금융공학은 단어 그대로 "금융 + 공학 = 금융공학"의 개념인데요,

다소 생소한 개념일수도 있는 금융공학을 쉽게 풀어서 정리해보려고 합니다.

먼저 금융과 공학이 무엇인지 정리해보고, 제가 생각하는 금융공학을 정의해보도록 하겠습니다.

### 금융이란?

**먼저, 금융이란 뭘까요?**

제가 생각하는 **금융은 자본의 흐름**입니다.

자본을 가지고 있는 사람이 자본이 필요한 사람에게 빌려주는 흐름을 말합니다.

자본은 쉽게 말해서 "돈"이며, 나무와 광물같은 원자재 등 돈으로 환산할 수 있는 것들, 심지어는 사람의 노동도 자본에 포함될 수 있습니다.

누군가는 자본을 빌려주면서 부가적인 수익을 올리고,

누군가는 자본을 빌려서 할 수 없었던 일을 해내면서 부가가치를 창출할 수 있습니다.

이러한 부가수익과 부가가치는 금융이 없었다면 존재하지 않았을 자본에 대한 기회비용이며, 금융으로 인해 비로소 실현될 수 있습니다.

이것을 측정할 수 있다면 금융의 가치가 될 것이며, 금융의 존재 이유가 됩니다.

#### 금융업

**그러면 금융업이란 뭘까요?**

금융업이란 **자본의 흐름이 원활하도록 돕는 것**을 업으로 하는 것을 말합니다.

자본의 흐름에는 여러 에로사항이 발생하게 되는데요,

대표적으로 자본을 빌려간 사람이 제때 안값거나, 자본을 빌려주고 싶어도 적당한 상대방을 찾기 어렵거나 하는 등의 문제들이 생기기 마련입니다.

이러한 문제를 해결하기 위해 누군가가 빌려주는 사람과 빌리는 사람을 연결해주고 제때 잘 값도록 보증해주기 시작했는데, 이러한 중개행위가 금융업의 시작이라고 볼 수 있습니다.

흔히 은행, 증권, 자산운용, 보험, 카드 등의 업계를 금융업계라고 부르는데, 각각의 업계가 하는 일은 모두 달라도 업의 본질은 자본을 빌려주는 사람과 빌리는 사람을 중개함으로써 자본이 원활하게 흐르도록 돕는 일입니다.

**은행**은 사람들이 저축한 예금을 돈이 필요한 사람들에게 빌려주는 일을 주로 하는데, 이 일의 본질은 예금과 대출이라는 간편한 창구를 만들어서, 돈을 빌리고 빌려주는 사람이 번거로울 필요 없이 간편하게 금융을 할 수 있도록 만드는 것입니다.

이 과정에서 은행은 대출에 대한 이자를 받고 예금에 대한 이자를 지급하는데, 그 차이인 "예대마진"이라는 중개수수료를 얻습니다.

사람들은 간편하게 예금과 대출을 이용하면서 편하게 금융을 이용하고 은행은 중개수수료를 얻게 되니, 예금에 대한 이자와 대출을 통해 생산한 부가가치 및 중개수수료를 합한 가치가 은행업을 통해 발생한 금융의 가치가 될 것 입니다.

**증권**회사는 보다 직접적으로 빌리는 사람과 빌려주는 사람을 중개하게 되는데, 은행이 예금과 대출을 매개채로 금융을 원활하게 했다면 증권회사는 주식이나 채권과 같은 "증권"이라는 매개체로 금융을 원활하게 합니다.

회사는 주식과 채권을 발행하고 투자자가 주식과 채권에 투자하는 것을 증권회사가 중개하는데, 여기서 회사가 돈을 빌리는 주체이며 투자자는 돈을 빌려주는 주체가 됩니다. 증권회사는 주식과 채권의 발행업무부터 투자자에게 홍보하고 판매하는 업무까지 담당하니, 금융이 원활하게 이루어지도록 돕는 일에 가장 부합해보입니다.

**보험**회사는 좀 달라보여도, 돈을 빌리는 사람은 미래에 불확실한 위험에 직면한 "나"이며, 돈을 빌려주는 사람은 그러한 위험에 대비하고 싶은 "나"라고 생각해보겠습니다.

"나"는 은행에 정기적인 예금을 통해 이를 대비할 수 있겠습니다. 그러나 미래의 불확실한 위험이 발생할 확률이 얼마나 될지, 그때 얼마나 돈이 필요할지 알기란 매우 어렵습니다.

여기서 보험회사의 역할이 생기게 됩니다. 미래의 불확실한 확률과 금액을 현재의 일정수준의 보험료로 환산한 다음, 현재의 "나"는 보험료만큼 보험회사에 돈을 빌려주게 되고 미래의 "나"에게 위험이 닥쳤을 때 보험회사에서 보험금을 빌리게 되는 구조입니다.

다른 금융회사도 자본의 흐름을 돕는 원리로 그 일의 본질을 설명할 수 있습니다.

#### 금융상품

다음으로, 금융상품은 무엇일까요?

우리나라의 자본시장법에서는 금융투자상품을 다음과 같이 정의하고 있습니다.

> “금융투자상품”이란 이익을 얻거나 손실을 회피할 목적으로 현재 또는 장래의 특정 시점에 금전, 그 밖의 재산적 가치가 있는 것을 지급하기로 약정함으로써 취득하는 권리로서, 그 권리를 취득하기 위하여 지급하였거나 지급하여야 할 금전등의 총액이 그 권리로부터 회수하였거나 회수할 수 있는 금전등의 총액을 초과하게 될 위험이 있는 것을 말한다.

일단... 법적인 내용은 저도 잘 모르지만 개념적으로 쉽게 받아들이기는 어려운 내용 같습니다.

저는 금융상품을 앞서 살펴본 자본의 흐름이라는 금융의 정의에 빗대어서 설명하려고 합니다.

금융상품이란 자본의 흐름을 돕는 매개체로서, 사람들이 사고 팔 수 있도록 상품화한 것을 말합니다.

다들 알고계시겠지만 주식과 채권, 펀드 등이 대표적인 금융상품이지요.

심지어 은행의 예금과 대출도 사람들이 사고 팔 수 있도록 상품화한다면, 금융상품이 될 수 있습니다.

양도성예금증서(CD)가 대표적인 예시입니다.

자본이 필요한 사람은 이러한 금융상품을 발행하게 되고, 자본을 빌려주는 사람은 금융상품을 구매함으로써 발행자에게 돈을 빌려주게 됩니다.

이후 금융상품의 특성에 따라 발행자는 구매자에게 이자를 지급하는 등으로 대가를 지급합니다.

금융상품이라는 매개체를 통해 자본의 흐름이 발생하는 것 입니다. 일반적으로 자본을 빌려주는 사람이 금융상품을 구매하는 것을 "투자"라고 합니다.

### 공학이란?

다음으로, 공학이란 무엇일까요?

제가 생각하는 공학이란, **자연현상을 이용해서 편리한 도구를 만드는 학문**입니다.

(저는 공학을 전혀 모르기때문에 어디까지나 제 주관적인 생각입니다.)

자연현상이란 물리, 화학 등 자연과학에서부터 최근에는 경제, 정치 등의 사회과학까지 모두 확장된 개념이고, 편리한 도구란 사람들을 편리하게 함으로써 부가가치를 창출하는 모든 것을 의미합니다.

흔히 공학이라고 하면 기계공학, 전자공학, 화학공학, 컴퓨터공학을 떠올리는데 "자연현상을 활용한 편리한 도구를 만드는 학문"의 관점에서 생각해봅시다.

기계공학 먼저 생각해보면, 이는 "운동"과 관련된 자연현상을 이용해서 "기계"라는 편리한 도구를 만드는 학문입니다.

전자공학은 "전자기력"과 관련된 자연현상을 이용해서 회로, 반도체 등등 편리한 도구를 만드는 학문이라고 할 수 있습니다.

컴퓨터공학 역시 전자기력과 수학, 논리학과 같은 자연현상을 이용해서 대단히 편리한 도구인 컴퓨터와 소프트웨어를 만드는 학문이라고 볼 수 있습니다.

이처럼 "공학"은 자연현상을 이용해서 부가가치를 창출하는 것으로 그 본질을 설명할 수 있습니다.

### 금융공학이란?

그럼, 금융공학은 어떻게 정의할 수 있을까요?

앞서 저는 금융을 자본의 흐름이라고 정의했고, 공학을 자연현상을 이용해서 편리한 도구를 만드는 것이라고 정의하였습니다.

이에 따르면 금융공학은 금융(자본의 흐름)과 관련한 자연현상을 이용해서 편리한 어떤 도구를 만드는 것 이겠지요.

아마도 **기존에 존재하는 자본의 흐름을 이용해서 새로운 자본의 흐름을 발생시키는 도구를 만드는 것**을 **금융공학**이라고 할 수 있을 것 같습니다.

예를 들자면, 은행이 만들어내는 자본의 흐름인 예금과 대출을 이용해서 여러 유동화증권(ABS, MBS ...)를 만들어내거나 주식이나 채권 기반의 여러 구조화증권들은 금융공학이 만들어낸 편리한 도구입니다.

마찬가지로 주식, 외환, 채권 등 기존의 금융상품을 기반으로 만들어진 새로운 금융상품들과 선물, 옵션 등 파생상품도 금융공학의 산물이라고 할 수 있습니다.

사람들은 금융공학의 산물을 이용하여 기존 자본의 흐름을 원활하게 돕거나, 새로운 투자기회를 제공함으로써 자본의 흐름을 만들어내기도 합니다.

이외에도, 주식 등 금융상품에 대한 전통적인 가격결정이론에 수학과 컴퓨터공학을 접목시켜서 새로운 가격결정이론을 만들어내고, 시장에서 새로운 거래전략을 개발하는 것도 금융공학이 하는 일이라고 할 수 있습니다.

시장조성(Market making) 전략이나 여러 차익거래 전략들은 사람들에게 새로운 투자기회를 제공하며, 시장에 유동성을 공급함으로써 모든 시장참여자의 거래비용을 절감시키기도 하니 새로운 자본의 흐름을 발생시키게 됩니다.

정리하자면, **금융공학**은 **금융의 속성을 이용해서 새로운 금융을 만드는 학문**이며, **기존의 금융을 돕고, 새로운 투자기회를 제공하는 것이 금융공학의 가치**입니다.