---
title: "금융공학의 여러 분야"
---

### Intro

앞서 저는 금융공학을 **자본의 흐름을 이용해서 새로운 금융을 만드는 학문**이라고 정의했습니다.

근데 사실 잘 안와닿을 것 같긴합니다. 제가 생각해도 모호한 것 같은데요,

그 이유를 생각해보니 금융공학에 대한 일반적인 인식과 동떨어져서 그런 것 같습니다.

아마 금융공학이라고 하면, *뭔가 수학적으로 주가를 예측하고, 이걸 컴퓨터로 구현한 다음, 남들보다 빨리 거래기회를 포착해서 돈을 버는 것*을 떠올리게 되는 것 같습니다.

즉, 금융공학은 자산을 프라이싱(pricing)하는 기술정도로 인식되고 있는 듯 합니다. 제가 생각하는 무언가 편리한 도구를 만드는 공학의 개념이랑은 좀 다르게 말입니다.

왜 그럴까요?

당연한 말이긴 하지만, 금융공학을 통해 새로운 금융을 만들어내기 위해서는 기존의 금융, 전통 자산에 대한 프라이싱이 반드시 필요하기 때문입니다. 주식이나 채권같은 전통 자산의 가격이 어떻게 결정되는지를 먼저 잘 알고, 이를 이용해서 새로운 금융상품을 만들어냄으로써 금융을 창출하는 것 이지요.

아마도 금융공학의 여러 가격결정 이론(pricing theory)를 이용해서 시장의 불균형을 찾아내고, 여기에서 돈을 버는 사람들이 점점 많아지면서 "금융공학은 프라이싱이다!" 라는 일반적인 인식이 자리잡지 않았을까 싶습니다.

물론 그 과정에서 시장의 불균형이 해소되고, 효율성이 높아지면서 선의의 다수의 투자자에게 이익이 돌아갈 수 있습니다. 그렇다면 여기서 돈을 버는 행위도 금융공학이라고 할 수 있겠죠. 시장조성(Market making)이나 유동성공급자(Liquidity provider)처럼 말입니다.

제가 말하고싶은건 프라이싱이 금융공학의 전부가 아니라는 겁니다. 금융공학은 본질적으로 새로운 금융을 만들어내는 편리한 도구이고, 프라이싱도 그 편리한 도구 중 하나입니다. 프라이싱을 통해 새로운 금융을 만들어내는 것이 금융공학이지, 프라이싱 자체가 목적이 될 수는 없습니다.

그럼 금융공학의 목적이라고 할 수 있는 새로운 금융 창출에는 어떤 것들이 있을까요?

이제 제가 생각하는 금융공학의 여러 분야를 알아보고, 또 프라이싱이 어떤 역할을 하는지, 어떤 방식으로 새로운 금융이 창출되는지 살펴보겠습니다.