{
  "hash": "636fa7430f873de002d39044038cc8c2",
  "result": {
    "engine": "knitr",
    "markdown": "# 채권분석 과제3 {.unnumbered}\n\n## Question 1\n\n투자자 A 는 표면금리 7% 미 국채를 액면 1,000 usd 구입하였다. 이 국채의 호가는 101-25+ 이다.\n결제일은 2024년 2월 5일이고, 쿠폰 지급일은 매년 4월 15일, 10월 15일이다. 지불한 invoice price(full price)를 센트까지만 구하시오.\n\n### Answer\n\n먼저, 액면 100당 Quote price(clean price)=101-25+=101+25/32+1/64=101.7969입니다.\n\n다음으로 경과이자(accrued interest)는 \"(지난이자지급일로부터 경과일)/이자지급주기*이자\"로 계산할 수 있습니다. (real/real 기반)\n\n경과일은 113일(2023.10.15~2024.02.05), 이자지급주기는 183일(2023-10-15~2024.04.15)이므로, 경과이자는 약 21.6120입니다.\n\n따라서, **Full price는 약 1039.58**입니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nclean <- (101+25/32+1/64)*10\nday_interest <- as.integer(ymd(20240415)-ymd(20231015))\nday_accrued <- as.integer(ymd(20240205)-ymd(20231015))\naccrued <- 35*day_accrued/day_interest\nfull <- clean+accrued\npaste(clean,accrued %>% round(6),full %>% round(6),sep=\" / \")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1017.96875 / 21.612022 / 1039.580772\"\n```\n\n\n:::\n:::\n\n\n## Question 2\n\n시장에서 현물이자율이 1년 4%, 2년 5% 라 가정하자. 그리고 1년 현물이자율의 연 변동(log rate)의 표준편차는 0.005 라 하자. 1년 후 1년 현물이자율의 시나리오를 $r_u, r_d$ 라 놓으면 시장 정보를반영하는 이 두 값을 구하시오.\n\n### Answer\n\n1년 후 현물이자율이 상승하였을 때를 $r_u$, 하락하였을 때를 $r_d$로 나눌 수 있으며 현물이자율의 로그수익률의 연표준편차가 0.005이므로, 아래와 같이 표현할 수 있습니다.\n\n$$r_u=r_de^{2\\sigma}=r_de^{0.01}$$\n\n한편, 2년 현물이자율에 투자한 zero-coupon bond와 1년 zero-coupon 및 1년 후에 다시 zero-coupon(forward)에 투자한 포트폴리오의 가치는 같아야 하므로, \n\n$$\\frac{100}{1.05^2}=\\frac{100}{(1.04)(1+E(r_1))}=0.5\\times \\frac{100}{1.04(1+r_u)}+0.5\\times \\frac{100}{1.04(1+r_d)}$$\n\n이분법을 통해 값을 추정하면, $r_u\\approx 6.04\\%.\\;r_d\\approx 5.98\\%$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninitial_d <- 0.01; initial_u <- 0.10\nr_d <- (initial_u+initial_d)/2; r_u <- r_d*exp(0.01)\n\nwhile(abs(0.5*100/(1.04*(1+r_u))+0.5*100/(1.04*(1+r_d))-100/1.05^2)>0.001){\n  if(0.5*100/(1.04*(1+r_u))+0.5*100/(1.04*(1+r_d))-100/1.05^2>0){initial_d <- r_d}\n  if(0.5*100/(1.04*(1+r_u))+0.5*100/(1.04*(1+r_d))-100/1.05^2<=0){initial_u <- r_d}\n  r_d <- (initial_u+initial_d)/2\n  r_u <- r_d*exp(0.01)}\npaste(r_u %>% round(4),r_d %>% round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"0.0604 0.0598\"\n```\n\n\n:::\n:::\n\n\n## Question 3\n\n2년 만기이고 표면금리가 8% 인 회사채를 가정하자. 표면금리의 지급은 연 1회이다. 그리고 이 회사채는 1년 시점에서 액면가 100 으로 call 할 수 있는 수의상환채이다. 신용위험 때문에 시장 에서는 이 회사채를 위에서 구한 금리모형에 스프레드를 더하여 그 가치를 계산한다.\n\n시장가가 101.9 라 할 때, static spread 와 option-adjusted spread 를 구하여라\n\n### Answer\n\n먼저, 수의상환부회사채의 시장가격 101.9와 문제 2의 zero-rate를 통해 **Static spread를 산출하면 아래와 같습니다.**\n\n$$101.9=\\frac{8}{(1.04+ss)}+\\frac{108}{(1.05+ss)^2}\\Rightarrow ss\\approx 1.988\\%$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmarket_price <- 101.9; initial_d <- 0.001; initial_u <- 0.1\nss <- (initial_u+initial_d)/2\n\nwhile(abs(8/(1.04+ss)+108/(1.05+ss)^2-market_price)>0.00001){\n  if(8/(1.04+ss)+108/(1.05+ss)^2-market_price>0){initial_d <- ss}\n  if(8/(1.04+ss)+108/(1.05+ss)^2-market_price<=0){initial_u <- ss}\n  ss <- (initial_u+initial_d)/2}\nss\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01988313\n```\n\n\n:::\n:::\n\n\n다음으로, 문제 2의 금리모형을 이용하여 OAS를 구해보겠습니다.\n\n먼저, OAS를 적용한 할인율은 zero rate + OAS로 표현할 수 있습니다.\n\n문제 2에 따라 1년 zero-rate는 4%, 상승시 $r_u=0.0604$, 하락시 $r_d=0.0598$이므로,\n\n$$r^*_1=0.04+OAS,\\;r^*_u=0.0604+OAS,\\;r_d^*=0.0598+OAS$$\n\n수의상환회사채는 1년 후 가격이 액면가보다 높으면 100에 상환되므로, $r_u^*,\\;r_d^*$가 8%보다 높은 경우 100에 상환됩니다.\n\n따라서, 수의상환회사채의 금리 상승/하락에 따른 가치평가는 아래와 같습니다.\n\n$$101.9=\\frac{1}{1+r_1^*}[8+\\frac{1}{2}(min\\{\\frac{108}{1+r_u^*},100\\}+min\\{\\frac{108}{1+r_d^*},100\\})]$$\n\n$$=\\frac{1}{1.04+OAS}[8+\\frac{1}{2}(min\\{\\frac{108}{1.0604+OAS},100\\}+min\\{\\frac{108}{1.0598+OAS},100\\})]$$\n\n$$\\Rightarrow OAS\\approx 1.978\\%$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninitial_d <- 0.001; initial_u <- 0.1\nOAS <- (initial_u+initial_d)/2\nwhile(abs((1/(1.04+OAS))*(8+0.5*(min(108/(1+r_u+OAS),100)+min(108/(1+r_d+OAS),100)))-market_price)>0.00001){\n  if((1/(1.04+OAS))*(8+0.5*(min(108/(1+r_u+OAS),100)+min(108/(1+r_d+OAS),100)))-market_price>0){initial_d <- OAS}\n  if((1/(1.04+OAS))*(8+0.5*(min(108/(1+r_u+OAS),100)+min(108/(1+r_d+OAS),100)))-market_price<=0){initial_u <- OAS}\n  OAS <- (initial_u+initial_d)/2\n}\nOAS\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01978343\n```\n\n\n:::\n:::\n\n\n::: {.callout-important title=\"Difference in each spreads\"}\nNominal spread, Static spread, Options adjusted spread\n\n1. Nominal spread : 단순히 국채 vs. 회사채의 YTM을 비교\n2. Static spread : zero rate + $\\alpha$를 계산, 기간구조를 반영하고있으나 향후 금리변동은 반영하지 않고 단순 현금흐름만 비교하므로, Zero-volatility spread라고도 함\n3. Options adjusted spread : 수의상환채의 옵션에 따른 향후 현금흐름 변동가능성을 고려하여 산출. 미래 금리변동으로 인해 옵션이 권리행사되는 경우를 감안하여 산출\n:::\n\n## Question 4\n\nPSA 방법에 따르면 PSA 스피드에 따라 월별 CPR 이 결정되고, 이는 다시 SMM 을 결정한다.\n강의노트의 PSA 방법론을 참조하여 다음의 SMM 표를 완성하시오.\n\n|월|100 PSA|60 PSA|230 PSA|\n|:--:|:--:|:--:|:--:|\n|1||||\n|20||||\n|200||||\n\n### Answer\n\nPSA란 연조기상환율(CPR:Conditional Prepayment Rate)이 매달 0.2% 증가하며, 6%까지 증가한 후 만기까지 지속되는 형태의 조기상환모형입니다.\n\n100 PSA가 기준이며, 50 PSA인 경우 매달 0.1%씩 증가 등 비율이 달라지게됩니다.\n\n다음으로, 월별조기상환율(SMM:Single Monthly Mortality rate)는 CPR을 월환산한 것으로, $1-SMM=(1-CPR)^\\frac{1}{12}$입니다.\n\n이에 따라 산출한 (1-SMM) 표는 아래와 같습니다.\n\n|월|100 PSA|60 PSA|230 PSA|\n|:--:|:--:|:--:|:--:|\n|1|$(1-0.2\\%)^\\frac{1}{12}$|$(1-0.2\\%\\times 0.6)^\\frac{1}{12}$|$(1-0.2\\%\\times 2.3)^\\frac{1}{12}$|\n|20|$(1-4\\%)^\\frac{1}{12}$|$(1-4\\%\\times 0.6)^\\frac{1}{12}$|$(1-4\\%\\times 2.3)^\\frac{1}{12}$|\n|200|$(1-6\\%)^\\frac{1}{12}$|$(1-6\\%\\times 0.6)^\\frac{1}{12}$|$(1-6\\%\\times 2.3)^\\frac{1}{12}$|\n\n이를 정리한 SMM 표는 아래와 같습니다.\n\n|월|100 PSA|60 PSA|230 PSA|\n|:--:|:--:|:--:|:--:|\n|1|0.000167|0.0001|0.000384|\n|20|0.003396|0.002022|0.008010|\n|200|0.005143|0.003051|0.012299|\n\n## Question 5\n\n다음의 CMO 는 9% 금리를 갖는 모기지 풀을 담보로 가지고 있다.\n\n|tranche|par(m USD)|coupon rate(%)|\n|:-----:|:--------:|:------------:|\n|A|300|7|\n|B|200|6.75|\n|C|200|7.25|\n|D|250|7.75|\n\n투자자가 금리 9% 의 notional IO 투자를 원한다고 하자. 해당 상품의 액면가를 계산하시오.\n\n### Answer\n\n먼저, CMO의 담보에서는 9%의 현금흐름이 발생하는 반면 각 tranche의 쿠폰은 9% 미만이므로 초과이자가 \\$17.125m만큼 발생합니다.\n\n이 초과이자분으로 금리 9%의 원금 없이 이자만 지급하는 구조화채권(Nominal IO)을 설계한다면, 액면가(명목금액)은 9%의 이자로 CMO의 초과수익인 \\$17.125m를 지급해야합니다.\n\n따라서, **액면가(명목금액)는 \\$17.125m/9%=\\$190.2778m**입니다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntotal_inflow=(300+200+200+250)*0.09\ntotal_outflow=300*0.07+200*0.0675+200*0.0725+250*0.0775\nexcess_interest=total_inflow-total_outflow\nnotional=excess_interest/0.09\npaste(excess_interest, notional, sep=\" / \")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"17.125 / 190.277777777778\"\n```\n\n\n:::\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}